// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiQxog4iCsBcPKUDV9woJF45AYQbk7n0Q',
    appId: '1:1030276429826:web:3ec863c18309e1e86e0f1b',
    messagingSenderId: '1030276429826',
    projectId: 'flutter-b301d',
    authDomain: 'flutter-b301d.firebaseapp.com',
    storageBucket: 'flutter-b301d.firebasestorage.app',
    measurementId: 'G-YD9GWTB2KX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA05Dy4Y-kCXgMSE1TMCqI9M0ibzNd4npM',
    appId: '1:1030276429826:android:ea793861924a43446e0f1b',
    messagingSenderId: '1030276429826',
    projectId: 'flutter-b301d',
    storageBucket: 'flutter-b301d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGzb0XGRVSQzmQz_MOPdiuA2LStOCQb8k',
    appId: '1:1030276429826:ios:794367cabe9e36706e0f1b',
    messagingSenderId: '1030276429826',
    projectId: 'flutter-b301d',
    storageBucket: 'flutter-b301d.firebasestorage.app',
    iosBundleId: 'com.example.tp0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGzb0XGRVSQzmQz_MOPdiuA2LStOCQb8k',
    appId: '1:1030276429826:ios:794367cabe9e36706e0f1b',
    messagingSenderId: '1030276429826',
    projectId: 'flutter-b301d',
    storageBucket: 'flutter-b301d.firebasestorage.app',
    iosBundleId: 'com.example.tp0',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiQxog4iCsBcPKUDV9woJF45AYQbk7n0Q',
    appId: '1:1030276429826:web:fc9aca8894f10fc16e0f1b',
    messagingSenderId: '1030276429826',
    projectId: 'flutter-b301d',
    authDomain: 'flutter-b301d.firebaseapp.com',
    storageBucket: 'flutter-b301d.firebasestorage.app',
    measurementId: 'G-R3LSK7L82N',
  );
}
